name: VirtualPack
main: net.drgnome.virtualpack.VPlugin
version: #VERSION#
author: Siguza
depend: [Vault]
softdepend: [ProtocolLib, WorldEdit, Multiverse-Core, PermissionsEx, GroupManager, PermissionsBukkit, iConomy, BOSEconomy]
permissions:

  vpack.all:
    description: "Gives FULL access to ALL VirtualPack features!"
    children:
      vpack.use.all: true
      vpack.use.enchanttable.free: true
      vpack.use.anvil.free: true
      vpack.keep.all: true
      vpack.send.all: true
      vpack.admin.all: true

  vpack.use:
    description: "Allows the basic use of VirtualPack"

  vpack.use.all:
    description: "Allows the use of all VirtualPack features"
    children:
      vpack.use: true
      vpack.use.workbench: true
      vpack.use.uncrafter: true
      vpack.use.enderchest: true
      vpack.use.enchanttable: true
      vpack.use.anvil: true
      vpack.use.materializer: true
      vpack.use.chest: true
      vpack.use.furnace: true
      vpack.use.brewingstand: true

  vpack.use.workbench:
    description: "Allows the use of the VirtualPack workbench"
    children:
      vpack.use: true

  vpack.use.uncrafter:
    description: "Allows the use of the VirtualPack uncrafter"
    children:
      vpack.use: true

  vpack.use.enderchest:
    description: "Allows the use of the VirtualPack enderchest"
    children:
      vpack.use: true

  vpack.use.enchanttable:
    description: "Allows the use of the VirtualPack enchantment table"
    children:
      vpack.use: true

  vpack.use.enchanttable.free:
    description: "Leaves your XP where they are when enchanting"
    children:
      vpack.use.enchanttable: true

  vpack.use.anvil:
    description: "Allows the use of the VirtualPack anvil"
    children:
      vpack.use: true

  vpack.use.materializer:
    description: "Allows the use of the VirtualPack materializer"
    children:
      vpack.use: true

  vpack.use.anvil.free:
    description: "Leaves your XP where they are when using the anvil"
    children:
      vpack.use.anvil: true

  vpack.use.chest:
    description: "Allows the use of the VirtualPack chests"
    children:
      vpack.use: true

  vpack.use.furnace:
    description: "Allows the use of the VirtualPack furnaces"
    children:
      vpack.use: true

  vpack.use.brewingstand:
    description: "Allows the use of the VirtualPack brewing stands"
    children:
      vpack.use: true

  vpack.sign.all:
    description: "Allows the use of all VirtualPack features"
    children:
      vpack.sign.workbench: true
      vpack.sign.uncrafter: true
      vpack.sign.enderchest: true
      vpack.sign.enchanttable: true
      vpack.sign.anvil: true
      vpack.sign.materializer: true
      vpack.sign.chest: true
      vpack.sign.furnace: true
      vpack.sign.brewingstand: true

  vpack.sign.workbench:
    description: "Allows the use of the VirtualPack workbench via sign"

  vpack.sign.uncrafter:
    description: "Allows the use of the VirtualPack uncrafter via sign"

  vpack.sign.enderchest:
    description: "Allows the use of the VirtualPack enderchest via sign"

  vpack.sign.enchanttable:
    description: "Allows the use of the VirtualPack enchantment table via sign"

  vpack.sign.anvil:
    description: "Allows the use of the VirtualPack anvil via sign"

  vpack.sign.materializer:
    description: "Allows the use of the VirtualPack materializer via sign"

  vpack.sign.chest:
    description: "Allows the use of the VirtualPack chests via sign"

  vpack.sign.furnace:
    description: "Allows the use of the VirtualPack furnaces via sign"

  vpack.sign.brewingstand:
    description: "Allows the use of the VirtualPack brewing stands via sign"

  vpack.keep.all:
    description: "Everything is kept upon death"
    children:
      vpack.keep.workbench: true
      vpack.keep.uncrafter: true
      vpack.keep.enderchest: true
      vpack.keep.enchanttable: true
      vpack.keep.anvil: true
      vpack.keep.materializer: true
      vpack.keep.chest: true
      vpack.keep.furnace: true
      vpack.keep.brewingstand: true

  vpack.keep.workbench:
    description: "Keep the workbench on death"

  vpack.keep.uncrafter:
    description: "Keep the uncrafter on death"

  vpack.keep.enderchest:
    description: "Keep the uncrafter on death"

  vpack.keep.enchanttable:
    description: "Keep the enchantment table on death"

  vpack.keep.anvil:
    description: "Keep the anvil on death"

  vpack.keep.materializer:
    description: "Keep the anvil on death"

  vpack.keep.chest:
    description: "Keep all chests on death"

  vpack.keep.furnace:
    description: "Keep all furnaces on death"

  vpack.keep.brewingstand:
    description: "Keep all brewing stands on death"

  vpack.stats:
    description: "Allows you to see other users stats"

  vpack.bypass.all:
    description: "Just everything starting with vpack.bypass"
    children:
      vpack.bypass.creative: true
      vpack.bypass.cut: true
      vpack.bypass.clean: true
      vpack.bypass.blacklist.all: true

  vpack.bypass.creative:
    description: "Allows you to use VirtualPack in creative mode even if creative mode is blocked"

  vpack.bypass.cut:
    description: "Excludes you from cuts"

  vpack.bypass.clean:
    description: "Excludes you from cleans"

  vpack.bypass.blacklist.all:
    description: "Allows you to ignore all blacklists"
    children:
      vpack.bypass.blacklist.uncrafter: true
      vpack.bypass.blacklist.store: true
      vpack.bypass.blacklist.materializer: true

  vpack.bypass.blacklist.uncrafter:
    description: "Allows you to ignore the uncrafter blacklist"

  vpack.bypass.blacklist.store:
    description: "Allows you to ignore the storing blacklist"

  vpack.bypass.blacklist.materializer:
    description: "Allows you to ignore the materializer blacklist"

  vpack.send:
    description: "Allows you to send items to other users chests"

  vpack.send.copy:
    description: "Allows you to copy and send items to other users chests"
    children:
      vpack.send: true

  vpack.send.all:
    description: "Allows you to copy and send items to all other users at the same time"
    children:
      vpack.send.copy: true

  vpack.admin:
    description: "Allows the use of Admin-features & doing a config reload"

  vpack.admin.all:
    description: "All Admin permissions for VirtualPack"
    children:
      vpack.admin.createsign: true
      vpack.admin.cut.force: true
      vpack.admin.clean: true
      vpack.admin.use.edit: true
      vpack.admin.give: true
      vpack.admin.take: true
      vpack.admin.forceopen: true
      vpack.admin.delete: true
      vpack.admin.stray: true
      vpack.stats: true
      vpack.update: true
      vpack.bypass.all: true

  vpack.admin.createsign:
    description: "Allows you to create VPack signs"
    children:
      vpack.admin: true

  vpack.admin.cut:
    description: "Allows you to remove tools that are over the maximum in the config"
    children:
      vpack.admin: true

  vpack.admin.clean:
    description: "Allows you to delete packs of users who haven't been online for some time"
    children:
      vpack.admin: true

  vpack.admin.cut.force:
    description: "Allows you to force tool cutting"
    children:
      vpack.admin.cut: true

  vpack.admin.use:
    description: "Allows you to open any users VirtualPack, but not to edit"
    children:
      vpack.admin: true

  vpack.admin.use.edit:
    description: "Allows you to open and edit any users VirtualPack"
    children:
      vpack.admin.use: true

  vpack.admin.give:
    description: "Allows you to give users stuff"
    children:
      vpack.admin: true

  vpack.admin.take:
    description: "Allows you to take stuff away from users"
    children:
      vpack.admin: true

  vpack.admin.forceopen:
    description: "Allows you to force another player to open a VirtualPack component"
    children:
      vpack.admin: true

  vpack.admin.delete:
    description: "Allows you to completely delete a users VirtualPack-account"
    children:
      vpack.admin: true

  vpack.admin.stray:
    description: "Allows you to deal with stray packs"
    children:
      vpack.admin: true

  vpack.update:
    description: "Notifies you of new VirtualPack versions"
