name: VirtualPack
main: net.drgnome.virtualpack.VPlugin
version: #VERSION#
author: Siguza
depend: [Vault]
softdepend: [WorldEdit, Multiverse-Core, PermissionsEx, GroupManager, PermissionsBukkit, iConomy, BOSEconomy]
permissions:
  vpack.use:
    description: Allows the basic use of VirtualPack
  vpack.use.all:
    description: Allows the use of all VirtualPack features
    children:
      vpack.use: true
      vpack.use.workbench: true
      vpack.use.uncrafter: true
      vpack.use.enchanttable: true
      vpack.use.anvil: true
      vpack.use.chest: true
      vpack.use.furnace: true
      vpack.use.brewingstand: true
  vpack.use.workbench:
    description: Allows the use of the VirtualPack workbench
    children:
      vpack.use: true
  vpack.use.uncrafter:
    description: Allows the use of the VirtualPack uncrafter
    children:
      vpack.use: true
  vpack.use.enchanttable:
    description: Allows the use of the VirtualPack enchantment table
    children:
      vpack.use: true
  vpack.use.enchanttable.free:
    description: Leaves your XP where they are
    children:
      vpack.use: true
      vpack.use.enchanttable: true
  vpack.use.anvil:
    description: Allows the use of the VirtualPack anvil
    children:
      vpack.use: true
  vpack.use.anvil.free:
    description: Leaves your XP where they are
    children:
      vpack.use: true
      vpack.use.anvil: true
  vpack.use.chest:
    description: Allows the use of the VirtualPack chests
    children:
      vpack.use: true
  vpack.use.furnace:
    description: Allows the use of the VirtualPack furnaces
    children:
      vpack.use: true
  vpack.use.brewingstand:
    description: Allows the use of the VirtualPack brewing stands
    children:
      vpack.use: true
  vpack.keep.all:
    decsription: Everything is kept upon death
    children:
      vpack.keep.workbench: true
      vpack.keep.uncrafter: true
      vpack.keep.enchanttable: true
      vpack.keep.anvil: true
      vpack.keep.chest: true
      vpack.keep.furnace: true
      vpack.keep.brewingstand: true
  vpack.keep.workbench:
    description: Keep the workbench on death
  vpack.keep.uncrafter:
    description: Keep the uncrafter on death
  vpack.keep.enchanttable:
    description: Keep the enchantment table on death
  vpack.keep.anvil:
    description: Keep the anvil on death
  vpack.keep.chest:
    description: Keep all chests on death
  vpack.keep.furnace:
    description: Keep all furnaces on death
  vpack.keep.brewingstand:
    description: Keep all brewing stands on death
  vpack.stats:
    description: Allows you to see other users stats
  vpack.send:
    description: Allows you to send items to other users chests
  vpack.admin:
    description: Allows the use of Admin-features & doing a config reload
  vpack.admin.all:
    description: Admin-Permissions for VirtualPack
    children:
      vpack.admin: true
      vpack.admin.use: true
      vpack.admin.give: true
      vpack.admin.take: true
      vpack.admin.delete: true
      vpack.update: true
  vpack.admin.use:
    description: Allows you to access any users VirtualPack
    children:
      vpack.admin: true
  vpack.admin.give:
    description: Allows you to give users stuff
    children:
      vpack.admin: true
  vpack.admin.take:
    description: Allows you to take stuff away from users
    children:
      vpack.admin: true
  vpack.admin.delete:
    description: Allows you to completely delete a users VirtualPack-account
    children:
      vpack.admin: true
  vpack.update:
    decsription: Notifies you of new VirtualPack versions